workflows:
  build-apk:
    name: Build APK - Chat N.A.Z Gold
    max_build_duration: 60
    instance_type: standard
    environment:
      flutter: stable
      xcode: latest
      vars:
        FLUTTER_BUILD_MODE: release
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build release APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
